apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qubool-kallyanam-auth-hpa
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-auth
    tier: backend
    service: auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qubool-kallyanam-auth
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 10  # Scale down by 10% max
        periodSeconds: 60
      - type: Pods
        value: 1   # Or remove 1 pod max
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100  # Scale up by 100% max
        periodSeconds: 15
      - type: Pods
        value: 2    # Or add 2 pods max
        periodSeconds: 60
      selectPolicy: Max