apiVersion: v1
kind: Service
metadata:
  name: qubool-kallyanam-auth-service
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-auth
    tier: backend
    service: auth
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "50051"
spec:
  selector:
    app: qubool-kallyanam-auth
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  type: ClusterIP
  sessionAffinity: None