apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qubool-kallyanam-user-hpa
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-user
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qubool-kallyanam-user
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 10  # Scale down 10% at a time
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately when needed
      policies:
      - type: Percent
        value: 100  # Can double the pods
        periodSeconds: 15
      - type: Pods
        value: 2  # Or add max 2 pods at once
        periodSeconds: 60