apiVersion: v1
kind: Service
metadata:
  name: qubool-kallyanam-user-service
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-user
    tier: backend
spec:
  selector:
    app: qubool-kallyanam-user
  ports:
  - port: 50053
    targetPort: 50053
    protocol: TCP
    name: grpc
  type: ClusterIP