grpc:
  port: 50051

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: qubool_kallyanam_auth
    sslmode: disable
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0

email:
  smtp_host: smtp.gmail.com
  smtp_port: 587
  username: your-email@gmail.com
  password: your-app-password
  from_email: noreply@quboolkallyanam.com
  from_name: Qubool Kallyanam