grpc:
  port: 50051

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: qubool_kallyanam_auth
    sslmode: disable
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0

email:
  smtp_host: mailhog
  smtp_port: 1025
  username: test@example.com
  password: password
  from: noreply@quboolkallyanam.com
  from_name: Qubool Kallyanam
otp:
  length: 6
  expiry_minutes: 10
auth:
  jwt:
    secret_key: "your-256-bit-secret-replace-in-production" # Use env var in production
    access_token_minutes: 15
    refresh_token_days: 7
    issuer: "qubool-kallyanam"
admin:
  default_email: "admin@quboolkallyanam.com"
  default_password: "Admin@123456" # This should be changed in production