apiVersion: v1
kind: Secret
metadata:
  name: qubool-kallyanam-secrets
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam
    environment: production
type: Opaque
stringData:
  # JWT Configuration
  jwt-secret: "${JWT_SECRET}"
  
  # Database Configuration (Cloud SQL)
  db-host: "${DB_HOST}"
  db-user: "${DB_USER}"
  db-password: "${DB_PASSWORD}"
  db-port: "${DB_PORT}"
  
  # Database Names
  auth-db-name: "qubool_kallyanam_auth"
  user-db-name: "qubool_kallyanam_user"
  payment-db-name: "qubool_kallyanam_payment"
  
  # Redis Configuration (Upstash)
  redis-url: "${REDIS_URL}"
  redis-token: "${REDIS_TOKEN}"
  
  # SMTP Configuration
  smtp-host: "${SMTP_HOST}"
  smtp-port: "${SMTP_PORT}"
  smtp-username: "${SMTP_USERNAME}"
  smtp-password: "${SMTP_PASSWORD}"
  email-from: "${EMAIL_FROM}"
  email-from-name: "${EMAIL_FROM_NAME}"
  
  # Razorpay Configuration
  razorpay-key-id: "${RAZORPAY_KEY_ID}"
  razorpay-key-secret: "${RAZORPAY_KEY_SECRET}"
  
  # Chat Database Configuration - Firestore for production
  firestore-project-id: "${PROJECT_ID}"
  
  # Keep MongoDB config for fallback/migration purposes 
  # mongodb-user: "${MONGODB_USER}"
  # mongodb-password: "${MONGODB_PASSWORD}"
  # mongodb-database: "qubool_kallyanam_chat"