apiVersion: apps/v1
kind: Deployment
metadata:
  name: qubool-kallyanam-chat
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-chat
    tier: backend
    service: chat
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: qubool-kallyanam-chat
  template:
    metadata:
      labels:
        app: qubool-kallyanam-chat
        tier: backend
        service: chat
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "50054"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: chat
        image: gcr.io/${PROJECT_ID}/qubool-kallyanam-chat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50054
          name: grpc
          protocol: TCP
        env:
        # Application Configuration
        - name: CONFIG_PATH
          value: "/app/configs/config.yaml"
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: qubool-kallyanam-config
              key: environment
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: qubool-kallyanam-config
              key: log-level
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: qubool-kallyanam-secrets
              key: jwt-secret
        
        # Database Configuration - Firestore for production
        - name: DATABASE_TYPE
          valueFrom:
            configMapKeyRef:
              name: qubool-kallyanam-config
              key: chat-database-type
        - name: FIRESTORE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: qubool-kallyanam-secrets
              key: firestore-project-id
        - name: FIRESTORE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: qubool-kallyanam-config
              key: firestore-database
        
        # Tracing Configuration
        - name: TRACING_ENABLED
          valueFrom:
            configMapKeyRef:
              name: qubool-kallyanam-config
              key: tracing-enabled
        - name: TRACING_SERVICE_NAME
          value: "qubool-kallyanam-chat"
        - name: TRACING_JAEGER_URL
          valueFrom:
            configMapKeyRef:
              name: qubool-kallyanam-config
              key: jaeger-endpoint
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        
        # Health Checks
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50054"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50054"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
          successThreshold: 1
        
        startupProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50054"]
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 12
        
        # Graceful Shutdown
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      
      # Pod Configuration
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      
      # Restart Policy
      restartPolicy: Always