apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qubool-kallyanam-chat-hpa
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-chat
    tier: backend
    service: chat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qubool-kallyanam-chat
  minReplicas: 1
  maxReplicas: 3  # Chat service may need fewer replicas than gateway
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60   # 1 minute  
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 1
        periodSeconds: 60