apiVersion: v1
kind: Service
metadata:
  name: qubool-kallyanam-chat-service
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-chat
    tier: backend
    service: chat
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "50054"
spec:
  selector:
    app: qubool-kallyanam-chat
  ports:
  - name: grpc
    port: 50054
    targetPort: 50054
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None