apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qubool-kallyanam-admin-hpa
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-admin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qubool-kallyanam-admin
  minReplicas: 1
  maxReplicas: 3  # Admin service doesn't need as much scaling as user-facing services
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 10  # Scale down by 10% at a time
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60  # Allow faster scale up for admin operations
      policies:
      - type: Percent
        value: 50  # Scale up by 50% at a time
        periodSeconds: 30
      - type: Pods
        value: 1  # Or add 1 pod at a time
        periodSeconds: 60