apiVersion: v1
kind: Service
metadata:
  name: qubool-kallyanam-admin-service
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-admin
    tier: backend
spec:
  selector:
    app: qubool-kallyanam-admin
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
    name: grpc
  type: ClusterIP
  # Internal service - only accessible within cluster
  # Gateway will route /api/v1/admin/* requests to this service