apiVersion: v1
kind: Service
metadata:
  name: qubool-kallyanam-payment-service
  namespace: qubool-kallyanam-production
  labels:
    app: qubool-kallyanam-payment
    tier: backend
spec:
  selector:
    app: qubool-kallyanam-payment
  ports:
  - port: 50055
    targetPort: 50055
    protocol: TCP
    name: grpc
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  type: ClusterIP