# services/chat/configs/config.yaml
server:
  host: "0.0.0.0"
  port: 50053
  timeout_seconds: 30

mongodb:
  host: "mongodb"
  port: 27017
  database: "chat"
  username: ""
  password: ""
  ssl_mode: "disable"
  timeout_seconds: 10
  connect_timeout: 10s
  server_selection_timeout: 5s

logging:
  level: debug
  development: true
  encoding: console
  output_paths:
    - stdout
  service_name: chat-service