# Add admin service configuration:
services:
  auth:
    address: "auth-service:50051"
  user:
    address: "user-service:50053"
  chat:
    address: "chat-service:50054"
  payment:
    address: "payment-service:50055"
  admin:                              
    address: "admin-service:50052"    

tracing:
  enabled: true
  service_name: "qubool-gateway"
  environment: "development"
  jaeger_url: "http://localhost:14268/api/traces"
  sample_rate: 1.0