global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8090']
        labels:
          service: 'gateway'

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8090']
        labels:
          service: 'auth'

  - job_name: 'user'
    static_configs:
      - targets: ['user:8090']
        labels:
          service: 'user'

  - job_name: 'chat'
    static_configs:
      - targets: ['chat:8090']
        labels:
          service: 'chat'

  - job_name: 'admin'
    static_configs:
      - targets: ['admin:8090']
        labels:
          service: 'admin'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'otel-collector'