services:
  # Database services
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qubool-net

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qubool-net

  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
    - "27017:27017"  # Explicitly expose MongoDB port
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts/mongodb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qubool-net

  # Application services
  auth-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.auth
    ports:
      - "50052:50052"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:50052/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - qubool-net

  user-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.user
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=users
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:50051/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - qubool-net

  chat-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.chat
    ports:
      - "50053:50053"
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:50053/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - qubool-net

  admin-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.admin
    ports:
      - "50054:50054"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=admin
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:50054/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - qubool-net

  gateway-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.gateway
    ports:
      - "8080:8080"
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy
      admin-service:
        condition: service_healthy
    environment:
      - SERVICE_USER=user-service:50051
      - SERVICE_AUTH=auth-service:50052
      - SERVICE_CHAT=chat-service:50053
      - SERVICE_ADMIN=admin-service:50054
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - qubool-net

networks:
  qubool-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  mongodb_data: