services:
  # API Gateway Service - starts last as it depends on all other services
  gateway:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.gateway
    container_name: qubool-gateway
    ports:
      - "8080:8080"
    environment:
      - common.environment=development
      - common.log_level=debug
      - common.debug=true
      - server.port=8080
      - server.host=0.0.0.0
      - gateway.request_timeout=30
      - gateway.max_request_size=10485760
      - gateway.enable_cors=true
      - gateway.rate_limit_requests_per_min=60
      - service_urls.auth_service=http://auth:8081
      - service_urls.user_service=http://user:8082
      - service_urls.chat_service=http://chat:8083
      - service_urls.admin_service=http://admin:8084
    networks:
      - qubool-network
    depends_on:
      auth:
        condition: service_healthy
      user:
        condition: service_healthy
      chat:
        condition: service_healthy
      admin:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Auth Service - depends on basic infrastructure
  auth:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.auth
    container_name: qubool-auth
    ports:
      - "8081:8081"
    environment:
      - common.environment=development
      - common.log_level=debug
      - common.debug=true
      - server.port=8081
      - server.host=0.0.0.0
      - auth.jwt_secret=development-jwt-secret-replace-in-production
      - auth.token_lifetime=60
    networks:
      - qubool-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # User Service - depends on basic infrastructure
  user:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.user
    container_name: qubool-user
    ports:
      - "8082:8082"
    environment:
      - common.environment=development
      - common.log_level=debug
      - common.debug=true
      - server.port=8082
      - server.host=0.0.0.0
      - user.profile_photo_max_size=5242880
      - user.default_avatar_url=/static/default-avatar.png
    networks:
      - qubool-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8082/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Chat Service - depends on basic infrastructure including MongoDB
  chat:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.chat
    container_name: qubool-chat
    ports:
      - "8083:8083"
    environment:
      - common.environment=development
      - common.log_level=debug
      - common.debug=true
      - server.port=8083
      - server.host=0.0.0.0
      - chat.max_message_length=1000
      - chat.message_rate_limit=60
      - chat.message_history_limit=100
      - chat.websocket_timeout=300
    networks:
      - qubool-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8083/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Admin Service - depends on basic infrastructure
  admin:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.admin
    container_name: qubool-admin
    ports:
      - "8084:8084"
    environment:
      - common.environment=development
      - common.log_level=debug
      - common.debug=true
      - server.port=8084
      - server.host=0.0.0.0
      - admin.session_timeout=60
      - admin.dashboard_cache_time=300
      - admin.admin_email_domain=qubool.com
    networks:
      - qubool-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8084/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: qubool-postgres
    environment:
      - POSTGRES_USER=qubool
      - POSTGRES_PASSWORD=qubool123
      - POSTGRES_DB=qubool_kallyanam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qubool-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qubool"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: qubool-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=qubool
      - MONGO_INITDB_ROOT_PASSWORD=qubool123
      - MONGO_INITDB_DATABASE=qubool_kallyanam
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - qubool-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: qubool-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - qubool-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  qubool-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  redis_data: