# services/gateway/configs/config.yaml
service:
  name: gateway-service
  environment: development
  version: "0.1.0"

server:
  host: "0.0.0.0"
  port: 8080
  timeout: 30

# Use network aliases that match the service names in docker-compose
services:
  # user_http: "user-service:50000"
  # user_grpc: "user-service:50001"
  auth_http: "auth-service:50010"
  # auth_grpc: "auth-service:50011"
  # chat_http: "chat-service:50020"
  # chat_grpc: "chat-service:50021"
  # admin_http: "admin-service:50030"
  # admin_grpc: "admin-service:50031"

logging:
  level: debug
  development: true
  encoding: console
  output_paths:
    - stdout
  service_name: gateway-service