grpc:
  port: 50055

http:
  port: 8081
  read_timeout_secs: 10
  write_timeout_secs: 10
  idle_timeout_secs: 60

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: qubool_kallyanam_payment
    sslmode: disable

razorpay:
  key_id: ${RAZORPAY_KEY_ID}
  key_secret: ${RAZORPAY_KEY_SECRET}

rabbitmq:
  dsn: "amqp://guest:guest@localhost:5672/"
  exchange_name: "qubool_events"

gateway:
  address: "http://localhost:8080"  # Gateway service address for redirects

plans:
  available:
    premium_365:
      id: "premium_365"
      name: "Premium Membership"
      duration_days: 365
      amount: 1000.0
      currency: "INR"
      description: "Premium membership with full access to all features"
      features:
        - "Unlimited profile views"
        - "Chat with all members"
        - "Advanced search filters"
        - "Priority customer support"
        - "Send unlimited messages"
        - "Access to exclusive events"
      is_active: true