grpc:
  port: 50053

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: qubool_kallyanam_user
    sslmode: disable
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0

rabbitmq:
  dsn: "amqp://guest:guest@localhost:5672/"
  exchange_name: "qubool_events"